export const EXERCISE_LIBRARY: Record<string, string[]> = {
  cardio: [
    'Running',
    'Swimming',
    'Cycling',
    'Rowing',
    'HIIT',
    'Jump Rope',
    'Elliptical',
    'Walking',
    'Stair Climber',
    'Boxing',
  ],
  strength: [
    'Squat',
    'Deadlift',
    'RDL',
    'Bench Press',
    'Pull-ups',
    'OHP',
    'Lunges',
    'Barbell Row',
    'Dips',
    'Hip Thrust',
    'Leg Press',
    'Lat Pulldown',
  ],
  stretch: [
    'Hip Flexor',
    'Hamstring',
    'Chest Opener',
    'Pigeon Pose',
    'Cobra',
    "Child's Pose",
    'Quad Stretch',
    'Figure-4',
    'Shoulder Cross',
    'Cat-Cow',
  ],
  balance: [
    'Single Leg Stand',
    'Bosu Ball Squat',
    'Tree Pose',
    'Warrior III',
    'Single Leg Deadlift',
    'Tandem Walk',
    'Standing Hip Abduction',
  ],
};
